import * as _87 from "./protobuf/any";
import * as _88 from "./protobuf/descriptor";
import * as _89 from "./protobuf/duration";
import * as _90 from "./protobuf/empty";
import * as _91 from "./protobuf/timestamp";
export declare namespace google {
    const protobuf: {
        Timestamp: {
            typeUrl: string;
            is(o: any): o is _91.Timestamp;
            isSDK(o: any): o is _91.TimestampSDKType;
            isAmino(o: any): o is _91.TimestampAmino;
            encode(message: _91.Timestamp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _91.Timestamp;
            fromPartial(object: Partial<_91.Timestamp>): _91.Timestamp;
            fromAmino(object: _91.TimestampAmino): _91.Timestamp;
            toAmino(message: _91.Timestamp): _91.TimestampAmino;
            fromAminoMsg(object: _91.TimestampAminoMsg): _91.Timestamp;
            fromProtoMsg(message: _91.TimestampProtoMsg): _91.Timestamp;
            toProto(message: _91.Timestamp): Uint8Array;
            toProtoMsg(message: _91.Timestamp): _91.TimestampProtoMsg;
        };
        Empty: {
            typeUrl: string;
            is(o: any): o is _90.Empty;
            isSDK(o: any): o is _90.EmptySDKType;
            isAmino(o: any): o is _90.EmptyAmino;
            encode(_: _90.Empty, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _90.Empty;
            fromPartial(_: Partial<_90.Empty>): _90.Empty;
            fromAmino(_: _90.EmptyAmino): _90.Empty;
            toAmino(_: _90.Empty): _90.EmptyAmino;
            fromAminoMsg(object: _90.EmptyAminoMsg): _90.Empty;
            fromProtoMsg(message: _90.EmptyProtoMsg): _90.Empty;
            toProto(message: _90.Empty): Uint8Array;
            toProtoMsg(message: _90.Empty): _90.EmptyProtoMsg;
        };
        Duration: {
            typeUrl: string;
            is(o: any): o is _89.Duration;
            isSDK(o: any): o is _89.DurationSDKType;
            isAmino(o: any): o is _89.DurationAmino;
            encode(message: _89.Duration, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _89.Duration;
            fromPartial(object: Partial<_89.Duration>): _89.Duration;
            fromAmino(object: _89.DurationAmino): _89.Duration;
            toAmino(message: _89.Duration): _89.DurationAmino;
            fromAminoMsg(object: _89.DurationAminoMsg): _89.Duration;
            fromProtoMsg(message: _89.DurationProtoMsg): _89.Duration;
            toProto(message: _89.Duration): Uint8Array;
            toProtoMsg(message: _89.Duration): _89.DurationProtoMsg;
        };
        fieldDescriptorProto_TypeFromJSON(object: any): _88.FieldDescriptorProto_Type;
        fieldDescriptorProto_TypeToJSON(object: _88.FieldDescriptorProto_Type): string;
        fieldDescriptorProto_LabelFromJSON(object: any): _88.FieldDescriptorProto_Label;
        fieldDescriptorProto_LabelToJSON(object: _88.FieldDescriptorProto_Label): string;
        fileOptions_OptimizeModeFromJSON(object: any): _88.FileOptions_OptimizeMode;
        fileOptions_OptimizeModeToJSON(object: _88.FileOptions_OptimizeMode): string;
        fieldOptions_CTypeFromJSON(object: any): _88.FieldOptions_CType;
        fieldOptions_CTypeToJSON(object: _88.FieldOptions_CType): string;
        fieldOptions_JSTypeFromJSON(object: any): _88.FieldOptions_JSType;
        fieldOptions_JSTypeToJSON(object: _88.FieldOptions_JSType): string;
        methodOptions_IdempotencyLevelFromJSON(object: any): _88.MethodOptions_IdempotencyLevel;
        methodOptions_IdempotencyLevelToJSON(object: _88.MethodOptions_IdempotencyLevel): string;
        FieldDescriptorProto_Type: typeof _88.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeSDKType: typeof _88.FieldDescriptorProto_Type;
        FieldDescriptorProto_TypeAmino: typeof _88.FieldDescriptorProto_Type;
        FieldDescriptorProto_Label: typeof _88.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelSDKType: typeof _88.FieldDescriptorProto_Label;
        FieldDescriptorProto_LabelAmino: typeof _88.FieldDescriptorProto_Label;
        FileOptions_OptimizeMode: typeof _88.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeSDKType: typeof _88.FileOptions_OptimizeMode;
        FileOptions_OptimizeModeAmino: typeof _88.FileOptions_OptimizeMode;
        FieldOptions_CType: typeof _88.FieldOptions_CType;
        FieldOptions_CTypeSDKType: typeof _88.FieldOptions_CType;
        FieldOptions_CTypeAmino: typeof _88.FieldOptions_CType;
        FieldOptions_JSType: typeof _88.FieldOptions_JSType;
        FieldOptions_JSTypeSDKType: typeof _88.FieldOptions_JSType;
        FieldOptions_JSTypeAmino: typeof _88.FieldOptions_JSType;
        MethodOptions_IdempotencyLevel: typeof _88.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelSDKType: typeof _88.MethodOptions_IdempotencyLevel;
        MethodOptions_IdempotencyLevelAmino: typeof _88.MethodOptions_IdempotencyLevel;
        FileDescriptorSet: {
            typeUrl: string;
            is(o: any): o is _88.FileDescriptorSet;
            isSDK(o: any): o is _88.FileDescriptorSetSDKType;
            isAmino(o: any): o is _88.FileDescriptorSetAmino;
            encode(message: _88.FileDescriptorSet, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.FileDescriptorSet;
            fromPartial(object: Partial<_88.FileDescriptorSet>): _88.FileDescriptorSet;
            fromAmino(object: _88.FileDescriptorSetAmino): _88.FileDescriptorSet;
            toAmino(message: _88.FileDescriptorSet): _88.FileDescriptorSetAmino;
            fromAminoMsg(object: _88.FileDescriptorSetAminoMsg): _88.FileDescriptorSet;
            fromProtoMsg(message: _88.FileDescriptorSetProtoMsg): _88.FileDescriptorSet;
            toProto(message: _88.FileDescriptorSet): Uint8Array;
            toProtoMsg(message: _88.FileDescriptorSet): _88.FileDescriptorSetProtoMsg;
        };
        FileDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.FileDescriptorProto;
            isSDK(o: any): o is _88.FileDescriptorProtoSDKType;
            isAmino(o: any): o is _88.FileDescriptorProtoAmino;
            encode(message: _88.FileDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.FileDescriptorProto;
            fromPartial(object: Partial<_88.FileDescriptorProto>): _88.FileDescriptorProto;
            fromAmino(object: _88.FileDescriptorProtoAmino): _88.FileDescriptorProto;
            toAmino(message: _88.FileDescriptorProto): _88.FileDescriptorProtoAmino;
            fromAminoMsg(object: _88.FileDescriptorProtoAminoMsg): _88.FileDescriptorProto;
            fromProtoMsg(message: _88.FileDescriptorProtoProtoMsg): _88.FileDescriptorProto;
            toProto(message: _88.FileDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.FileDescriptorProto): _88.FileDescriptorProtoProtoMsg;
        };
        DescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.DescriptorProto;
            isSDK(o: any): o is _88.DescriptorProtoSDKType;
            isAmino(o: any): o is _88.DescriptorProtoAmino;
            encode(message: _88.DescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.DescriptorProto;
            fromPartial(object: Partial<_88.DescriptorProto>): _88.DescriptorProto;
            fromAmino(object: _88.DescriptorProtoAmino): _88.DescriptorProto;
            toAmino(message: _88.DescriptorProto): _88.DescriptorProtoAmino;
            fromAminoMsg(object: _88.DescriptorProtoAminoMsg): _88.DescriptorProto;
            fromProtoMsg(message: _88.DescriptorProtoProtoMsg): _88.DescriptorProto;
            toProto(message: _88.DescriptorProto): Uint8Array;
            toProtoMsg(message: _88.DescriptorProto): _88.DescriptorProtoProtoMsg;
        };
        DescriptorProto_ExtensionRange: {
            typeUrl: string;
            is(o: any): o is _88.DescriptorProto_ExtensionRange;
            isSDK(o: any): o is _88.DescriptorProto_ExtensionRangeSDKType;
            isAmino(o: any): o is _88.DescriptorProto_ExtensionRangeAmino;
            encode(message: _88.DescriptorProto_ExtensionRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.DescriptorProto_ExtensionRange;
            fromPartial(object: Partial<_88.DescriptorProto_ExtensionRange>): _88.DescriptorProto_ExtensionRange;
            fromAmino(object: _88.DescriptorProto_ExtensionRangeAmino): _88.DescriptorProto_ExtensionRange;
            toAmino(message: _88.DescriptorProto_ExtensionRange): _88.DescriptorProto_ExtensionRangeAmino;
            fromAminoMsg(object: _88.DescriptorProto_ExtensionRangeAminoMsg): _88.DescriptorProto_ExtensionRange;
            fromProtoMsg(message: _88.DescriptorProto_ExtensionRangeProtoMsg): _88.DescriptorProto_ExtensionRange;
            toProto(message: _88.DescriptorProto_ExtensionRange): Uint8Array;
            toProtoMsg(message: _88.DescriptorProto_ExtensionRange): _88.DescriptorProto_ExtensionRangeProtoMsg;
        };
        DescriptorProto_ReservedRange: {
            typeUrl: string;
            is(o: any): o is _88.DescriptorProto_ReservedRange;
            isSDK(o: any): o is _88.DescriptorProto_ReservedRangeSDKType;
            isAmino(o: any): o is _88.DescriptorProto_ReservedRangeAmino;
            encode(message: _88.DescriptorProto_ReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.DescriptorProto_ReservedRange;
            fromPartial(object: Partial<_88.DescriptorProto_ReservedRange>): _88.DescriptorProto_ReservedRange;
            fromAmino(object: _88.DescriptorProto_ReservedRangeAmino): _88.DescriptorProto_ReservedRange;
            toAmino(message: _88.DescriptorProto_ReservedRange): _88.DescriptorProto_ReservedRangeAmino;
            fromAminoMsg(object: _88.DescriptorProto_ReservedRangeAminoMsg): _88.DescriptorProto_ReservedRange;
            fromProtoMsg(message: _88.DescriptorProto_ReservedRangeProtoMsg): _88.DescriptorProto_ReservedRange;
            toProto(message: _88.DescriptorProto_ReservedRange): Uint8Array;
            toProtoMsg(message: _88.DescriptorProto_ReservedRange): _88.DescriptorProto_ReservedRangeProtoMsg;
        };
        ExtensionRangeOptions: {
            typeUrl: string;
            is(o: any): o is _88.ExtensionRangeOptions;
            isSDK(o: any): o is _88.ExtensionRangeOptionsSDKType;
            isAmino(o: any): o is _88.ExtensionRangeOptionsAmino;
            encode(message: _88.ExtensionRangeOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.ExtensionRangeOptions;
            fromPartial(object: Partial<_88.ExtensionRangeOptions>): _88.ExtensionRangeOptions;
            fromAmino(object: _88.ExtensionRangeOptionsAmino): _88.ExtensionRangeOptions;
            toAmino(message: _88.ExtensionRangeOptions): _88.ExtensionRangeOptionsAmino;
            fromAminoMsg(object: _88.ExtensionRangeOptionsAminoMsg): _88.ExtensionRangeOptions;
            fromProtoMsg(message: _88.ExtensionRangeOptionsProtoMsg): _88.ExtensionRangeOptions;
            toProto(message: _88.ExtensionRangeOptions): Uint8Array;
            toProtoMsg(message: _88.ExtensionRangeOptions): _88.ExtensionRangeOptionsProtoMsg;
        };
        FieldDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.FieldDescriptorProto;
            isSDK(o: any): o is _88.FieldDescriptorProtoSDKType;
            isAmino(o: any): o is _88.FieldDescriptorProtoAmino;
            encode(message: _88.FieldDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.FieldDescriptorProto;
            fromPartial(object: Partial<_88.FieldDescriptorProto>): _88.FieldDescriptorProto;
            fromAmino(object: _88.FieldDescriptorProtoAmino): _88.FieldDescriptorProto;
            toAmino(message: _88.FieldDescriptorProto): _88.FieldDescriptorProtoAmino;
            fromAminoMsg(object: _88.FieldDescriptorProtoAminoMsg): _88.FieldDescriptorProto;
            fromProtoMsg(message: _88.FieldDescriptorProtoProtoMsg): _88.FieldDescriptorProto;
            toProto(message: _88.FieldDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.FieldDescriptorProto): _88.FieldDescriptorProtoProtoMsg;
        };
        OneofDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.OneofDescriptorProto;
            isSDK(o: any): o is _88.OneofDescriptorProtoSDKType;
            isAmino(o: any): o is _88.OneofDescriptorProtoAmino;
            encode(message: _88.OneofDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.OneofDescriptorProto;
            fromPartial(object: Partial<_88.OneofDescriptorProto>): _88.OneofDescriptorProto;
            fromAmino(object: _88.OneofDescriptorProtoAmino): _88.OneofDescriptorProto;
            toAmino(message: _88.OneofDescriptorProto): _88.OneofDescriptorProtoAmino;
            fromAminoMsg(object: _88.OneofDescriptorProtoAminoMsg): _88.OneofDescriptorProto;
            fromProtoMsg(message: _88.OneofDescriptorProtoProtoMsg): _88.OneofDescriptorProto;
            toProto(message: _88.OneofDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.OneofDescriptorProto): _88.OneofDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.EnumDescriptorProto;
            isSDK(o: any): o is _88.EnumDescriptorProtoSDKType;
            isAmino(o: any): o is _88.EnumDescriptorProtoAmino;
            encode(message: _88.EnumDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.EnumDescriptorProto;
            fromPartial(object: Partial<_88.EnumDescriptorProto>): _88.EnumDescriptorProto;
            fromAmino(object: _88.EnumDescriptorProtoAmino): _88.EnumDescriptorProto;
            toAmino(message: _88.EnumDescriptorProto): _88.EnumDescriptorProtoAmino;
            fromAminoMsg(object: _88.EnumDescriptorProtoAminoMsg): _88.EnumDescriptorProto;
            fromProtoMsg(message: _88.EnumDescriptorProtoProtoMsg): _88.EnumDescriptorProto;
            toProto(message: _88.EnumDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.EnumDescriptorProto): _88.EnumDescriptorProtoProtoMsg;
        };
        EnumDescriptorProto_EnumReservedRange: {
            typeUrl: string;
            is(o: any): o is _88.EnumDescriptorProto_EnumReservedRange;
            isSDK(o: any): o is _88.EnumDescriptorProto_EnumReservedRangeSDKType;
            isAmino(o: any): o is _88.EnumDescriptorProto_EnumReservedRangeAmino;
            encode(message: _88.EnumDescriptorProto_EnumReservedRange, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.EnumDescriptorProto_EnumReservedRange;
            fromPartial(object: Partial<_88.EnumDescriptorProto_EnumReservedRange>): _88.EnumDescriptorProto_EnumReservedRange;
            fromAmino(object: _88.EnumDescriptorProto_EnumReservedRangeAmino): _88.EnumDescriptorProto_EnumReservedRange;
            toAmino(message: _88.EnumDescriptorProto_EnumReservedRange): _88.EnumDescriptorProto_EnumReservedRangeAmino;
            fromAminoMsg(object: _88.EnumDescriptorProto_EnumReservedRangeAminoMsg): _88.EnumDescriptorProto_EnumReservedRange;
            fromProtoMsg(message: _88.EnumDescriptorProto_EnumReservedRangeProtoMsg): _88.EnumDescriptorProto_EnumReservedRange;
            toProto(message: _88.EnumDescriptorProto_EnumReservedRange): Uint8Array;
            toProtoMsg(message: _88.EnumDescriptorProto_EnumReservedRange): _88.EnumDescriptorProto_EnumReservedRangeProtoMsg;
        };
        EnumValueDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.EnumValueDescriptorProto;
            isSDK(o: any): o is _88.EnumValueDescriptorProtoSDKType;
            isAmino(o: any): o is _88.EnumValueDescriptorProtoAmino;
            encode(message: _88.EnumValueDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.EnumValueDescriptorProto;
            fromPartial(object: Partial<_88.EnumValueDescriptorProto>): _88.EnumValueDescriptorProto;
            fromAmino(object: _88.EnumValueDescriptorProtoAmino): _88.EnumValueDescriptorProto;
            toAmino(message: _88.EnumValueDescriptorProto): _88.EnumValueDescriptorProtoAmino;
            fromAminoMsg(object: _88.EnumValueDescriptorProtoAminoMsg): _88.EnumValueDescriptorProto;
            fromProtoMsg(message: _88.EnumValueDescriptorProtoProtoMsg): _88.EnumValueDescriptorProto;
            toProto(message: _88.EnumValueDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.EnumValueDescriptorProto): _88.EnumValueDescriptorProtoProtoMsg;
        };
        ServiceDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.ServiceDescriptorProto;
            isSDK(o: any): o is _88.ServiceDescriptorProtoSDKType;
            isAmino(o: any): o is _88.ServiceDescriptorProtoAmino;
            encode(message: _88.ServiceDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.ServiceDescriptorProto;
            fromPartial(object: Partial<_88.ServiceDescriptorProto>): _88.ServiceDescriptorProto;
            fromAmino(object: _88.ServiceDescriptorProtoAmino): _88.ServiceDescriptorProto;
            toAmino(message: _88.ServiceDescriptorProto): _88.ServiceDescriptorProtoAmino;
            fromAminoMsg(object: _88.ServiceDescriptorProtoAminoMsg): _88.ServiceDescriptorProto;
            fromProtoMsg(message: _88.ServiceDescriptorProtoProtoMsg): _88.ServiceDescriptorProto;
            toProto(message: _88.ServiceDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.ServiceDescriptorProto): _88.ServiceDescriptorProtoProtoMsg;
        };
        MethodDescriptorProto: {
            typeUrl: string;
            is(o: any): o is _88.MethodDescriptorProto;
            isSDK(o: any): o is _88.MethodDescriptorProtoSDKType;
            isAmino(o: any): o is _88.MethodDescriptorProtoAmino;
            encode(message: _88.MethodDescriptorProto, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.MethodDescriptorProto;
            fromPartial(object: Partial<_88.MethodDescriptorProto>): _88.MethodDescriptorProto;
            fromAmino(object: _88.MethodDescriptorProtoAmino): _88.MethodDescriptorProto;
            toAmino(message: _88.MethodDescriptorProto): _88.MethodDescriptorProtoAmino;
            fromAminoMsg(object: _88.MethodDescriptorProtoAminoMsg): _88.MethodDescriptorProto;
            fromProtoMsg(message: _88.MethodDescriptorProtoProtoMsg): _88.MethodDescriptorProto;
            toProto(message: _88.MethodDescriptorProto): Uint8Array;
            toProtoMsg(message: _88.MethodDescriptorProto): _88.MethodDescriptorProtoProtoMsg;
        };
        FileOptions: {
            typeUrl: string;
            is(o: any): o is _88.FileOptions;
            isSDK(o: any): o is _88.FileOptionsSDKType;
            isAmino(o: any): o is _88.FileOptionsAmino;
            encode(message: _88.FileOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.FileOptions;
            fromPartial(object: Partial<_88.FileOptions>): _88.FileOptions;
            fromAmino(object: _88.FileOptionsAmino): _88.FileOptions;
            toAmino(message: _88.FileOptions): _88.FileOptionsAmino;
            fromAminoMsg(object: _88.FileOptionsAminoMsg): _88.FileOptions;
            fromProtoMsg(message: _88.FileOptionsProtoMsg): _88.FileOptions;
            toProto(message: _88.FileOptions): Uint8Array;
            toProtoMsg(message: _88.FileOptions): _88.FileOptionsProtoMsg;
        };
        MessageOptions: {
            typeUrl: string;
            is(o: any): o is _88.MessageOptions;
            isSDK(o: any): o is _88.MessageOptionsSDKType;
            isAmino(o: any): o is _88.MessageOptionsAmino;
            encode(message: _88.MessageOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.MessageOptions;
            fromPartial(object: Partial<_88.MessageOptions>): _88.MessageOptions;
            fromAmino(object: _88.MessageOptionsAmino): _88.MessageOptions;
            toAmino(message: _88.MessageOptions): _88.MessageOptionsAmino;
            fromAminoMsg(object: _88.MessageOptionsAminoMsg): _88.MessageOptions;
            fromProtoMsg(message: _88.MessageOptionsProtoMsg): _88.MessageOptions;
            toProto(message: _88.MessageOptions): Uint8Array;
            toProtoMsg(message: _88.MessageOptions): _88.MessageOptionsProtoMsg;
        };
        FieldOptions: {
            typeUrl: string;
            is(o: any): o is _88.FieldOptions;
            isSDK(o: any): o is _88.FieldOptionsSDKType;
            isAmino(o: any): o is _88.FieldOptionsAmino;
            encode(message: _88.FieldOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.FieldOptions;
            fromPartial(object: Partial<_88.FieldOptions>): _88.FieldOptions;
            fromAmino(object: _88.FieldOptionsAmino): _88.FieldOptions;
            toAmino(message: _88.FieldOptions): _88.FieldOptionsAmino;
            fromAminoMsg(object: _88.FieldOptionsAminoMsg): _88.FieldOptions;
            fromProtoMsg(message: _88.FieldOptionsProtoMsg): _88.FieldOptions;
            toProto(message: _88.FieldOptions): Uint8Array;
            toProtoMsg(message: _88.FieldOptions): _88.FieldOptionsProtoMsg;
        };
        OneofOptions: {
            typeUrl: string;
            is(o: any): o is _88.OneofOptions;
            isSDK(o: any): o is _88.OneofOptionsSDKType;
            isAmino(o: any): o is _88.OneofOptionsAmino;
            encode(message: _88.OneofOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.OneofOptions;
            fromPartial(object: Partial<_88.OneofOptions>): _88.OneofOptions;
            fromAmino(object: _88.OneofOptionsAmino): _88.OneofOptions;
            toAmino(message: _88.OneofOptions): _88.OneofOptionsAmino;
            fromAminoMsg(object: _88.OneofOptionsAminoMsg): _88.OneofOptions;
            fromProtoMsg(message: _88.OneofOptionsProtoMsg): _88.OneofOptions;
            toProto(message: _88.OneofOptions): Uint8Array;
            toProtoMsg(message: _88.OneofOptions): _88.OneofOptionsProtoMsg;
        };
        EnumOptions: {
            typeUrl: string;
            is(o: any): o is _88.EnumOptions;
            isSDK(o: any): o is _88.EnumOptionsSDKType;
            isAmino(o: any): o is _88.EnumOptionsAmino;
            encode(message: _88.EnumOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.EnumOptions;
            fromPartial(object: Partial<_88.EnumOptions>): _88.EnumOptions;
            fromAmino(object: _88.EnumOptionsAmino): _88.EnumOptions;
            toAmino(message: _88.EnumOptions): _88.EnumOptionsAmino;
            fromAminoMsg(object: _88.EnumOptionsAminoMsg): _88.EnumOptions;
            fromProtoMsg(message: _88.EnumOptionsProtoMsg): _88.EnumOptions;
            toProto(message: _88.EnumOptions): Uint8Array;
            toProtoMsg(message: _88.EnumOptions): _88.EnumOptionsProtoMsg;
        };
        EnumValueOptions: {
            typeUrl: string;
            is(o: any): o is _88.EnumValueOptions;
            isSDK(o: any): o is _88.EnumValueOptionsSDKType;
            isAmino(o: any): o is _88.EnumValueOptionsAmino;
            encode(message: _88.EnumValueOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.EnumValueOptions;
            fromPartial(object: Partial<_88.EnumValueOptions>): _88.EnumValueOptions;
            fromAmino(object: _88.EnumValueOptionsAmino): _88.EnumValueOptions;
            toAmino(message: _88.EnumValueOptions): _88.EnumValueOptionsAmino;
            fromAminoMsg(object: _88.EnumValueOptionsAminoMsg): _88.EnumValueOptions;
            fromProtoMsg(message: _88.EnumValueOptionsProtoMsg): _88.EnumValueOptions;
            toProto(message: _88.EnumValueOptions): Uint8Array;
            toProtoMsg(message: _88.EnumValueOptions): _88.EnumValueOptionsProtoMsg;
        };
        ServiceOptions: {
            typeUrl: string;
            is(o: any): o is _88.ServiceOptions;
            isSDK(o: any): o is _88.ServiceOptionsSDKType;
            isAmino(o: any): o is _88.ServiceOptionsAmino;
            encode(message: _88.ServiceOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.ServiceOptions;
            fromPartial(object: Partial<_88.ServiceOptions>): _88.ServiceOptions;
            fromAmino(object: _88.ServiceOptionsAmino): _88.ServiceOptions;
            toAmino(message: _88.ServiceOptions): _88.ServiceOptionsAmino;
            fromAminoMsg(object: _88.ServiceOptionsAminoMsg): _88.ServiceOptions;
            fromProtoMsg(message: _88.ServiceOptionsProtoMsg): _88.ServiceOptions;
            toProto(message: _88.ServiceOptions): Uint8Array;
            toProtoMsg(message: _88.ServiceOptions): _88.ServiceOptionsProtoMsg;
        };
        MethodOptions: {
            typeUrl: string;
            is(o: any): o is _88.MethodOptions;
            isSDK(o: any): o is _88.MethodOptionsSDKType;
            isAmino(o: any): o is _88.MethodOptionsAmino;
            encode(message: _88.MethodOptions, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.MethodOptions;
            fromPartial(object: Partial<_88.MethodOptions>): _88.MethodOptions;
            fromAmino(object: _88.MethodOptionsAmino): _88.MethodOptions;
            toAmino(message: _88.MethodOptions): _88.MethodOptionsAmino;
            fromAminoMsg(object: _88.MethodOptionsAminoMsg): _88.MethodOptions;
            fromProtoMsg(message: _88.MethodOptionsProtoMsg): _88.MethodOptions;
            toProto(message: _88.MethodOptions): Uint8Array;
            toProtoMsg(message: _88.MethodOptions): _88.MethodOptionsProtoMsg;
        };
        UninterpretedOption: {
            typeUrl: string;
            is(o: any): o is _88.UninterpretedOption;
            isSDK(o: any): o is _88.UninterpretedOptionSDKType;
            isAmino(o: any): o is _88.UninterpretedOptionAmino;
            encode(message: _88.UninterpretedOption, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.UninterpretedOption;
            fromPartial(object: Partial<_88.UninterpretedOption>): _88.UninterpretedOption;
            fromAmino(object: _88.UninterpretedOptionAmino): _88.UninterpretedOption;
            toAmino(message: _88.UninterpretedOption): _88.UninterpretedOptionAmino;
            fromAminoMsg(object: _88.UninterpretedOptionAminoMsg): _88.UninterpretedOption;
            fromProtoMsg(message: _88.UninterpretedOptionProtoMsg): _88.UninterpretedOption;
            toProto(message: _88.UninterpretedOption): Uint8Array;
            toProtoMsg(message: _88.UninterpretedOption): _88.UninterpretedOptionProtoMsg;
        };
        UninterpretedOption_NamePart: {
            typeUrl: string;
            is(o: any): o is _88.UninterpretedOption_NamePart;
            isSDK(o: any): o is _88.UninterpretedOption_NamePartSDKType;
            isAmino(o: any): o is _88.UninterpretedOption_NamePartAmino;
            encode(message: _88.UninterpretedOption_NamePart, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.UninterpretedOption_NamePart;
            fromPartial(object: Partial<_88.UninterpretedOption_NamePart>): _88.UninterpretedOption_NamePart;
            fromAmino(object: _88.UninterpretedOption_NamePartAmino): _88.UninterpretedOption_NamePart;
            toAmino(message: _88.UninterpretedOption_NamePart): _88.UninterpretedOption_NamePartAmino;
            fromAminoMsg(object: _88.UninterpretedOption_NamePartAminoMsg): _88.UninterpretedOption_NamePart;
            fromProtoMsg(message: _88.UninterpretedOption_NamePartProtoMsg): _88.UninterpretedOption_NamePart;
            toProto(message: _88.UninterpretedOption_NamePart): Uint8Array;
            toProtoMsg(message: _88.UninterpretedOption_NamePart): _88.UninterpretedOption_NamePartProtoMsg;
        };
        SourceCodeInfo: {
            typeUrl: string;
            is(o: any): o is _88.SourceCodeInfo;
            isSDK(o: any): o is _88.SourceCodeInfoSDKType;
            isAmino(o: any): o is _88.SourceCodeInfoAmino;
            encode(message: _88.SourceCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.SourceCodeInfo;
            fromPartial(object: Partial<_88.SourceCodeInfo>): _88.SourceCodeInfo;
            fromAmino(object: _88.SourceCodeInfoAmino): _88.SourceCodeInfo;
            toAmino(message: _88.SourceCodeInfo): _88.SourceCodeInfoAmino;
            fromAminoMsg(object: _88.SourceCodeInfoAminoMsg): _88.SourceCodeInfo;
            fromProtoMsg(message: _88.SourceCodeInfoProtoMsg): _88.SourceCodeInfo;
            toProto(message: _88.SourceCodeInfo): Uint8Array;
            toProtoMsg(message: _88.SourceCodeInfo): _88.SourceCodeInfoProtoMsg;
        };
        SourceCodeInfo_Location: {
            typeUrl: string;
            is(o: any): o is _88.SourceCodeInfo_Location;
            isSDK(o: any): o is _88.SourceCodeInfo_LocationSDKType;
            isAmino(o: any): o is _88.SourceCodeInfo_LocationAmino;
            encode(message: _88.SourceCodeInfo_Location, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.SourceCodeInfo_Location;
            fromPartial(object: Partial<_88.SourceCodeInfo_Location>): _88.SourceCodeInfo_Location;
            fromAmino(object: _88.SourceCodeInfo_LocationAmino): _88.SourceCodeInfo_Location;
            toAmino(message: _88.SourceCodeInfo_Location): _88.SourceCodeInfo_LocationAmino;
            fromAminoMsg(object: _88.SourceCodeInfo_LocationAminoMsg): _88.SourceCodeInfo_Location;
            fromProtoMsg(message: _88.SourceCodeInfo_LocationProtoMsg): _88.SourceCodeInfo_Location;
            toProto(message: _88.SourceCodeInfo_Location): Uint8Array;
            toProtoMsg(message: _88.SourceCodeInfo_Location): _88.SourceCodeInfo_LocationProtoMsg;
        };
        GeneratedCodeInfo: {
            typeUrl: string;
            is(o: any): o is _88.GeneratedCodeInfo;
            isSDK(o: any): o is _88.GeneratedCodeInfoSDKType;
            isAmino(o: any): o is _88.GeneratedCodeInfoAmino;
            encode(message: _88.GeneratedCodeInfo, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.GeneratedCodeInfo;
            fromPartial(object: Partial<_88.GeneratedCodeInfo>): _88.GeneratedCodeInfo;
            fromAmino(object: _88.GeneratedCodeInfoAmino): _88.GeneratedCodeInfo;
            toAmino(message: _88.GeneratedCodeInfo): _88.GeneratedCodeInfoAmino;
            fromAminoMsg(object: _88.GeneratedCodeInfoAminoMsg): _88.GeneratedCodeInfo;
            fromProtoMsg(message: _88.GeneratedCodeInfoProtoMsg): _88.GeneratedCodeInfo;
            toProto(message: _88.GeneratedCodeInfo): Uint8Array;
            toProtoMsg(message: _88.GeneratedCodeInfo): _88.GeneratedCodeInfoProtoMsg;
        };
        GeneratedCodeInfo_Annotation: {
            typeUrl: string;
            is(o: any): o is _88.GeneratedCodeInfo_Annotation;
            isSDK(o: any): o is _88.GeneratedCodeInfo_AnnotationSDKType;
            isAmino(o: any): o is _88.GeneratedCodeInfo_AnnotationAmino;
            encode(message: _88.GeneratedCodeInfo_Annotation, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _88.GeneratedCodeInfo_Annotation;
            fromPartial(object: Partial<_88.GeneratedCodeInfo_Annotation>): _88.GeneratedCodeInfo_Annotation;
            fromAmino(object: _88.GeneratedCodeInfo_AnnotationAmino): _88.GeneratedCodeInfo_Annotation;
            toAmino(message: _88.GeneratedCodeInfo_Annotation): _88.GeneratedCodeInfo_AnnotationAmino;
            fromAminoMsg(object: _88.GeneratedCodeInfo_AnnotationAminoMsg): _88.GeneratedCodeInfo_Annotation;
            fromProtoMsg(message: _88.GeneratedCodeInfo_AnnotationProtoMsg): _88.GeneratedCodeInfo_Annotation;
            toProto(message: _88.GeneratedCodeInfo_Annotation): Uint8Array;
            toProtoMsg(message: _88.GeneratedCodeInfo_Annotation): _88.GeneratedCodeInfo_AnnotationProtoMsg;
        };
        Any: {
            typeUrl: string;
            is(o: any): o is _87.Any;
            isSDK(o: any): o is _87.AnySDKType;
            isAmino(o: any): o is _87.AnyAmino;
            encode(message: _87.Any, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
            decode(input: import("..").BinaryReader | Uint8Array, length?: number): _87.Any;
            fromPartial(object: Partial<_87.Any>): _87.Any;
            fromAmino(object: _87.AnyAmino): _87.Any;
            toAmino(message: _87.Any): _87.AnyAmino;
            fromAminoMsg(object: _87.AnyAminoMsg): _87.Any;
            fromProtoMsg(message: _87.AnyProtoMsg): _87.Any;
            toProto(message: _87.Any): Uint8Array;
            toProtoMsg(message: _87.Any): _87.AnyProtoMsg;
        };
    };
}
