/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        babelConfig: false,
        tsconfig: 'tsconfig.json',
      },
    ],
  },
  transformIgnorePatterns: [`/node_modules/*`],
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  modulePathIgnorePatterns: ['dist/*'],
  // SCAFFOLD TEST SKIPPED — `__tests__/fundjs-react.test.js` was a
  // placeholder calling `require('..')()` (treating the package as a
  // single function), which never matched the actual exports (React
  // hooks + chain bundles). It's been broken since the package
  // contents were generated by telescope. **Real coverage** for the
  // published bindings lives in the broadcast-verified harness
  // referenced in the Stage 10 mainchain tracker
  // (`/tmp/fundjs-broadcast.mjs` against the vaxildan binary, 12/12
  // PASS). Operator action item: commit that harness as a proper
  // integration test post-publish so canonical coverage lives in the
  // repo rather than `/tmp/`.
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/__tests__/fundjs-react\\.test\\.(js|ts)$',
  ],
};
