import * as _18 from "../confio/proofs";
export declare const ics23: {
    hashOpFromJSON(object: any): _18.HashOp;
    hashOpToJSON(object: _18.HashOp): string;
    lengthOpFromJSON(object: any): _18.LengthOp;
    lengthOpToJSON(object: _18.LengthOp): string;
    HashOp: typeof _18.HashOp;
    HashOpSDKType: typeof _18.HashOp;
    HashOpAmino: typeof _18.HashOp;
    LengthOp: typeof _18.LengthOp;
    LengthOpSDKType: typeof _18.LengthOp;
    LengthOpAmino: typeof _18.LengthOp;
    ExistenceProof: {
        typeUrl: string;
        is(o: any): o is _18.ExistenceProof;
        isSDK(o: any): o is _18.ExistenceProofSDKType;
        isAmino(o: any): o is _18.ExistenceProofAmino;
        encode(message: _18.ExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.ExistenceProof;
        fromPartial(object: Partial<_18.ExistenceProof>): _18.ExistenceProof;
        fromAmino(object: _18.ExistenceProofAmino): _18.ExistenceProof;
        toAmino(message: _18.ExistenceProof): _18.ExistenceProofAmino;
        fromAminoMsg(object: _18.ExistenceProofAminoMsg): _18.ExistenceProof;
        fromProtoMsg(message: _18.ExistenceProofProtoMsg): _18.ExistenceProof;
        toProto(message: _18.ExistenceProof): Uint8Array;
        toProtoMsg(message: _18.ExistenceProof): _18.ExistenceProofProtoMsg;
    };
    NonExistenceProof: {
        typeUrl: string;
        is(o: any): o is _18.NonExistenceProof;
        isSDK(o: any): o is _18.NonExistenceProofSDKType;
        isAmino(o: any): o is _18.NonExistenceProofAmino;
        encode(message: _18.NonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.NonExistenceProof;
        fromPartial(object: Partial<_18.NonExistenceProof>): _18.NonExistenceProof;
        fromAmino(object: _18.NonExistenceProofAmino): _18.NonExistenceProof;
        toAmino(message: _18.NonExistenceProof): _18.NonExistenceProofAmino;
        fromAminoMsg(object: _18.NonExistenceProofAminoMsg): _18.NonExistenceProof;
        fromProtoMsg(message: _18.NonExistenceProofProtoMsg): _18.NonExistenceProof;
        toProto(message: _18.NonExistenceProof): Uint8Array;
        toProtoMsg(message: _18.NonExistenceProof): _18.NonExistenceProofProtoMsg;
    };
    CommitmentProof: {
        typeUrl: string;
        is(o: any): o is _18.CommitmentProof;
        isSDK(o: any): o is _18.CommitmentProofSDKType;
        isAmino(o: any): o is _18.CommitmentProofAmino;
        encode(message: _18.CommitmentProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.CommitmentProof;
        fromPartial(object: Partial<_18.CommitmentProof>): _18.CommitmentProof;
        fromAmino(object: _18.CommitmentProofAmino): _18.CommitmentProof;
        toAmino(message: _18.CommitmentProof): _18.CommitmentProofAmino;
        fromAminoMsg(object: _18.CommitmentProofAminoMsg): _18.CommitmentProof;
        fromProtoMsg(message: _18.CommitmentProofProtoMsg): _18.CommitmentProof;
        toProto(message: _18.CommitmentProof): Uint8Array;
        toProtoMsg(message: _18.CommitmentProof): _18.CommitmentProofProtoMsg;
    };
    LeafOp: {
        typeUrl: string;
        is(o: any): o is _18.LeafOp;
        isSDK(o: any): o is _18.LeafOpSDKType;
        isAmino(o: any): o is _18.LeafOpAmino;
        encode(message: _18.LeafOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.LeafOp;
        fromPartial(object: Partial<_18.LeafOp>): _18.LeafOp;
        fromAmino(object: _18.LeafOpAmino): _18.LeafOp;
        toAmino(message: _18.LeafOp): _18.LeafOpAmino;
        fromAminoMsg(object: _18.LeafOpAminoMsg): _18.LeafOp;
        fromProtoMsg(message: _18.LeafOpProtoMsg): _18.LeafOp;
        toProto(message: _18.LeafOp): Uint8Array;
        toProtoMsg(message: _18.LeafOp): _18.LeafOpProtoMsg;
    };
    InnerOp: {
        typeUrl: string;
        is(o: any): o is _18.InnerOp;
        isSDK(o: any): o is _18.InnerOpSDKType;
        isAmino(o: any): o is _18.InnerOpAmino;
        encode(message: _18.InnerOp, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.InnerOp;
        fromPartial(object: Partial<_18.InnerOp>): _18.InnerOp;
        fromAmino(object: _18.InnerOpAmino): _18.InnerOp;
        toAmino(message: _18.InnerOp): _18.InnerOpAmino;
        fromAminoMsg(object: _18.InnerOpAminoMsg): _18.InnerOp;
        fromProtoMsg(message: _18.InnerOpProtoMsg): _18.InnerOp;
        toProto(message: _18.InnerOp): Uint8Array;
        toProtoMsg(message: _18.InnerOp): _18.InnerOpProtoMsg;
    };
    ProofSpec: {
        typeUrl: string;
        is(o: any): o is _18.ProofSpec;
        isSDK(o: any): o is _18.ProofSpecSDKType;
        isAmino(o: any): o is _18.ProofSpecAmino;
        encode(message: _18.ProofSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.ProofSpec;
        fromPartial(object: Partial<_18.ProofSpec>): _18.ProofSpec;
        fromAmino(object: _18.ProofSpecAmino): _18.ProofSpec;
        toAmino(message: _18.ProofSpec): _18.ProofSpecAmino;
        fromAminoMsg(object: _18.ProofSpecAminoMsg): _18.ProofSpec;
        fromProtoMsg(message: _18.ProofSpecProtoMsg): _18.ProofSpec;
        toProto(message: _18.ProofSpec): Uint8Array;
        toProtoMsg(message: _18.ProofSpec): _18.ProofSpecProtoMsg;
    };
    InnerSpec: {
        typeUrl: string;
        is(o: any): o is _18.InnerSpec;
        isSDK(o: any): o is _18.InnerSpecSDKType;
        isAmino(o: any): o is _18.InnerSpecAmino;
        encode(message: _18.InnerSpec, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.InnerSpec;
        fromPartial(object: Partial<_18.InnerSpec>): _18.InnerSpec;
        fromAmino(object: _18.InnerSpecAmino): _18.InnerSpec;
        toAmino(message: _18.InnerSpec): _18.InnerSpecAmino;
        fromAminoMsg(object: _18.InnerSpecAminoMsg): _18.InnerSpec;
        fromProtoMsg(message: _18.InnerSpecProtoMsg): _18.InnerSpec;
        toProto(message: _18.InnerSpec): Uint8Array;
        toProtoMsg(message: _18.InnerSpec): _18.InnerSpecProtoMsg;
    };
    BatchProof: {
        typeUrl: string;
        is(o: any): o is _18.BatchProof;
        isSDK(o: any): o is _18.BatchProofSDKType;
        isAmino(o: any): o is _18.BatchProofAmino;
        encode(message: _18.BatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.BatchProof;
        fromPartial(object: Partial<_18.BatchProof>): _18.BatchProof;
        fromAmino(object: _18.BatchProofAmino): _18.BatchProof;
        toAmino(message: _18.BatchProof): _18.BatchProofAmino;
        fromAminoMsg(object: _18.BatchProofAminoMsg): _18.BatchProof;
        fromProtoMsg(message: _18.BatchProofProtoMsg): _18.BatchProof;
        toProto(message: _18.BatchProof): Uint8Array;
        toProtoMsg(message: _18.BatchProof): _18.BatchProofProtoMsg;
    };
    BatchEntry: {
        typeUrl: string;
        is(o: any): o is _18.BatchEntry;
        isSDK(o: any): o is _18.BatchEntrySDKType;
        isAmino(o: any): o is _18.BatchEntryAmino;
        encode(message: _18.BatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.BatchEntry;
        fromPartial(object: Partial<_18.BatchEntry>): _18.BatchEntry;
        fromAmino(object: _18.BatchEntryAmino): _18.BatchEntry;
        toAmino(message: _18.BatchEntry): _18.BatchEntryAmino;
        fromAminoMsg(object: _18.BatchEntryAminoMsg): _18.BatchEntry;
        fromProtoMsg(message: _18.BatchEntryProtoMsg): _18.BatchEntry;
        toProto(message: _18.BatchEntry): Uint8Array;
        toProtoMsg(message: _18.BatchEntry): _18.BatchEntryProtoMsg;
    };
    CompressedBatchProof: {
        typeUrl: string;
        is(o: any): o is _18.CompressedBatchProof;
        isSDK(o: any): o is _18.CompressedBatchProofSDKType;
        isAmino(o: any): o is _18.CompressedBatchProofAmino;
        encode(message: _18.CompressedBatchProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.CompressedBatchProof;
        fromPartial(object: Partial<_18.CompressedBatchProof>): _18.CompressedBatchProof;
        fromAmino(object: _18.CompressedBatchProofAmino): _18.CompressedBatchProof;
        toAmino(message: _18.CompressedBatchProof): _18.CompressedBatchProofAmino;
        fromAminoMsg(object: _18.CompressedBatchProofAminoMsg): _18.CompressedBatchProof;
        fromProtoMsg(message: _18.CompressedBatchProofProtoMsg): _18.CompressedBatchProof;
        toProto(message: _18.CompressedBatchProof): Uint8Array;
        toProtoMsg(message: _18.CompressedBatchProof): _18.CompressedBatchProofProtoMsg;
    };
    CompressedBatchEntry: {
        typeUrl: string;
        is(o: any): o is _18.CompressedBatchEntry;
        isSDK(o: any): o is _18.CompressedBatchEntrySDKType;
        isAmino(o: any): o is _18.CompressedBatchEntryAmino;
        encode(message: _18.CompressedBatchEntry, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.CompressedBatchEntry;
        fromPartial(object: Partial<_18.CompressedBatchEntry>): _18.CompressedBatchEntry;
        fromAmino(object: _18.CompressedBatchEntryAmino): _18.CompressedBatchEntry;
        toAmino(message: _18.CompressedBatchEntry): _18.CompressedBatchEntryAmino;
        fromAminoMsg(object: _18.CompressedBatchEntryAminoMsg): _18.CompressedBatchEntry;
        fromProtoMsg(message: _18.CompressedBatchEntryProtoMsg): _18.CompressedBatchEntry;
        toProto(message: _18.CompressedBatchEntry): Uint8Array;
        toProtoMsg(message: _18.CompressedBatchEntry): _18.CompressedBatchEntryProtoMsg;
    };
    CompressedExistenceProof: {
        typeUrl: string;
        is(o: any): o is _18.CompressedExistenceProof;
        isSDK(o: any): o is _18.CompressedExistenceProofSDKType;
        isAmino(o: any): o is _18.CompressedExistenceProofAmino;
        encode(message: _18.CompressedExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.CompressedExistenceProof;
        fromPartial(object: Partial<_18.CompressedExistenceProof>): _18.CompressedExistenceProof;
        fromAmino(object: _18.CompressedExistenceProofAmino): _18.CompressedExistenceProof;
        toAmino(message: _18.CompressedExistenceProof): _18.CompressedExistenceProofAmino;
        fromAminoMsg(object: _18.CompressedExistenceProofAminoMsg): _18.CompressedExistenceProof;
        fromProtoMsg(message: _18.CompressedExistenceProofProtoMsg): _18.CompressedExistenceProof;
        toProto(message: _18.CompressedExistenceProof): Uint8Array;
        toProtoMsg(message: _18.CompressedExistenceProof): _18.CompressedExistenceProofProtoMsg;
    };
    CompressedNonExistenceProof: {
        typeUrl: string;
        is(o: any): o is _18.CompressedNonExistenceProof;
        isSDK(o: any): o is _18.CompressedNonExistenceProofSDKType;
        isAmino(o: any): o is _18.CompressedNonExistenceProofAmino;
        encode(message: _18.CompressedNonExistenceProof, writer?: import("..").BinaryWriter): import("..").BinaryWriter;
        decode(input: import("..").BinaryReader | Uint8Array, length?: number): _18.CompressedNonExistenceProof;
        fromPartial(object: Partial<_18.CompressedNonExistenceProof>): _18.CompressedNonExistenceProof;
        fromAmino(object: _18.CompressedNonExistenceProofAmino): _18.CompressedNonExistenceProof;
        toAmino(message: _18.CompressedNonExistenceProof): _18.CompressedNonExistenceProofAmino;
        fromAminoMsg(object: _18.CompressedNonExistenceProofAminoMsg): _18.CompressedNonExistenceProof;
        fromProtoMsg(message: _18.CompressedNonExistenceProofProtoMsg): _18.CompressedNonExistenceProof;
        toProto(message: _18.CompressedNonExistenceProof): Uint8Array;
        toProtoMsg(message: _18.CompressedNonExistenceProof): _18.CompressedNonExistenceProofProtoMsg;
    };
};
