"use strict";
//@ts-nocheck
/**
* This file and any referenced files were automatically generated by @cosmology/telescope@1.8.3
* DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
* and run the transpile command or npm scripts command that is used to regenerate this bundle.
*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.createRpcClient = exports.getRpcClient = exports.getRpcEndpointKey = void 0;
const stargate_1 = require("@cosmjs/stargate");
const tendermint_rpc_1 = require("@cosmjs/tendermint-rpc");
const _rpcClients = {};
const getRpcEndpointKey = (rpcEndpoint) => {
    if (typeof rpcEndpoint === 'string') {
        return rpcEndpoint;
    }
    else if (!!rpcEndpoint) {
        //@ts-ignore
        return rpcEndpoint.url;
    }
};
exports.getRpcEndpointKey = getRpcEndpointKey;
const getRpcClient = async (rpcEndpoint) => {
    const key = (0, exports.getRpcEndpointKey)(rpcEndpoint);
    if (!key)
        return;
    if (_rpcClients.hasOwnProperty(key)) {
        return _rpcClients[key];
    }
    const cometClient = await (0, tendermint_rpc_1.connectComet)(rpcEndpoint);
    //@ts-ignore
    const client = new stargate_1.QueryClient(cometClient);
    const rpc = (0, stargate_1.createProtobufRpcClient)(client);
    _rpcClients[key] = rpc;
    return rpc;
};
exports.getRpcClient = getRpcClient;
const createRpcClient = async (rpcEndpoint) => {
    const cometClient = await (0, tendermint_rpc_1.connectComet)(rpcEndpoint);
    //@ts-ignore
    const client = new stargate_1.QueryClient(cometClient);
    const rpc = (0, stargate_1.createProtobufRpcClient)(client);
    return rpc;
};
exports.createRpcClient = createRpcClient;
